<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerSX7j80y\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerSX7j80y/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerSX7j80y.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerSX7j80y\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerSX7j80y\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'SX7j80y',
    'container.build_id' => '11560e28',
    'container.build_time' => 1637277089,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerSX7j80y');
